
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: randomtree_development


test:
  <<: *default
  database: randomtree_test

production:
  <<: *default
  database: randomtree_production
